# Generated by Django 3.1.5 on 2021-03-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_auto_20210311_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='30', null=True, upload_to='images/', width_field='40'),
        ),
    ]
