# Generated by Django 3.1.5 on 2021-03-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0008_auto_20210318_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
