# Generated by Django 3.1.5 on 2021-03-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210308_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phoneno',
        ),
    ]
